# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'
    - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
      spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.3.1/bundles/@yarnpkg/plugin-after-install.js'

yarnPath: .yarn/releases/yarn-3.2.2.cjs

afterInstall: npx patch-package
