# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none

# The `resources` specify the location and version of the 1ES PT.
resources:
    repositories:
        - repository: 1esPipelines
          type: git
          name: 1ESPipelineTemplates/1ESPipelineTemplates
          ref: refs/tags/release

extends:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
    parameters:
        # Update the pool with your team's 1ES hosted pool.
        pool:
            os: linux
            image: ubuntu-20.04
            name: AccessibilityInsights-ubuntu-20.04

        stages:
            - stage: Stage
              jobs:
                  - job: 'BuildArtifactsAndRunUnitTests'
                    steps:
                        - template: ./azure-pipeline/build-artifacts-and-run-tests-job.yaml
