# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: $(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
    - job: 'BuildArtifacts'
      pool:
          vmImage: 'ubuntu-16.04'
          demands: npm
      steps:
          - template: ./azure-pipeline/build-artifacts-job-steps.yaml

    - job: 'Test'
      pool:
          vmImage: 'ubuntu-16.04'
          demands: npm
      steps:
          - template: ./azure-pipeline/test-job-steps.yaml
