# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: $(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
    - job: 'BuildArtifactsAndRunSomeTests'
      pool:
          vmImage: 'ubuntu-16.04'
          demands: npm
      steps:
          - template: ./azure-pipeline/build-artifacts-and-some-tests-job-steps.yaml
            parameters: { totalSlices: 4, slicesToRun: '[0]' }

    - job: 'RunRemainingTests'
      pool:
          vmImage: 'ubuntu-16.04'
          demands: npm
      steps:
          - template: ./azure-pipeline/remaining-tests-job.yaml
            parameters: { totalSlices: 4, slicesToRun: '[1,2,3]' }
