# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
    - job: 'BuildArtifactsAndRunUnitTests'
      pool:
          vmImage: 'ubuntu-latest'
          demands: npm
      steps:
          - template: ./azure-pipeline/build-artifacts-and-run-tests-job.yaml
