pool:
    vmImage: 'Ubuntu-16.04'
    demands: npm

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: 10.x
      displayName: 'Use Node 10.x'

    - script: |
          yarn install --frozen-lockfile
      displayName: 'install dependencies'

    - script: |
          yarn format-check
      displayName: check code formatting

    - script: |
          yarn clean
      displayName: clean

    - script: |
          # 1st '--' needed for yarn since, yarn won't pass the first argument if it is --; 2nd '--' lets lerna to pass on anything after this as args;
          yarn build -- -- --env.version=$(Build.BuildId)
      displayName: build

    - script: |
          yarn lint
      displayName: run linter

    - script: |
          yarn test --ci --coverage
      displayName: run unit tests

    - task: PublishTestResults@2
      inputs:
          testResultsFiles: 'test-results/unit/junit.xml'
          searchFolder: '$(Build.SourcesDirectory)'
          testRunTitle: unit tests
      condition: always()
      displayName: publish unit test results

    - task: NuGetToolInstaller@0
      displayName: 'Install NuGet'

    - task: PublishCodeCoverageResults@1
      inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(Build.SourcesDirectory)/test-results/unit/coverage/cobertura-coverage.xml'
      displayName: publish code coverage

    - script: |
          yarn build-image
      workingDirectory: 'packages/scanner-function'
      displayName: build scanner function docker image

    - task: Docker@1
      inputs:
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistryName).azurecr.io
          command: login
      displayName: Container registry login
      condition: and(succeeded(), in(variables['publishImage'], 'true'))

    - script: |
          docker tag scanner $(azureContainerRegistryName).azurecr.io/$(imageName)
          docker tag scanner $(azureContainerRegistryName).azurecr.io/$(imageName):$(Build.BuildId)
          docker push $(azureContainerRegistryName).azurecr.io/$(imageName)
          docker push $(azureContainerRegistryName).azurecr.io/$(imageName):$(Build.BuildId)
      displayName: 'Push image to container registry'
      condition: and(succeeded(), in(variables['publishImage'], 'true'))
