pool:
    vmImage: 'Ubuntu-16.04'
    demands: npm

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: 10.x
      displayName: 'Use Node 10.x'

    - task: Npm@1
      inputs:
          command: custom
          customCommand: ci
      displayName: 'install root dependencies'

    - task: Npm@1
      inputs:
          command: custom
          customCommand: run bootstrap -- --ci
      displayName: 'install packages dependencies'

    - task: Npm@1
      inputs:
          command: custom
          customCommand: run lint
      displayName: run linter

    - task: Npm@1
      inputs:
          command: custom
          customCommand: run format-check
      displayName: check code formatting

    - task: Npm@1
      inputs:
          command: custom
          customCommand: run clean
      displayName: clean

    - task: Npm@1
      inputs:
          command: custom
          # 1st '--' denotes args for root npm; 2nd '--' denotes args for lerna; 3rd '--' denots args for the sub project npm script
          customCommand: run build -- -- -- --env.version=$(Build.BuildId)
      displayName: build

    - task: Npm@1
      inputs:
          command: custom
          customCommand: run test -- --ci
      displayName: run unit tests

    - task: PublishTestResults@2
      inputs:
          testResultsFiles: '**/test-results/unit/junit.xml'
          testRunTitle: unit tests
      condition: always()
      displayName: publish unit test results

    - task: PublishCodeCoverageResults@1
      inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '**/test-results/unit/coverage/cobertura-coverage.xml'
          failIfCoverageEmpty: true
      displayName: publish code coverage

    - task: Npm@1
      inputs:
          command: custom
          customCommand: run build-image
          workingDir: 'packages/scanner-function'
      displayName: build scanner function docker image

    - task: Docker@1
      inputs:
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistryName).azurecr.io
          command: login
      displayName: Container registry login
      condition: and(succeeded(), in(variables['publishImage'], 'true'))

    - script: |
          docker tag scanner $(azureContainerRegistryName).azurecr.io/$(imageName)
          docker tag scanner $(azureContainerRegistryName).azurecr.io/$(imageName):$(Build.BuildId)
          docker push $(azureContainerRegistryName).azurecr.io/$(imageName)
          docker push $(azureContainerRegistryName).azurecr.io/$(imageName):$(Build.BuildId)
      displayName: 'Push image to container registry'
      condition: and(succeeded(), in(variables['publishImage'], 'true'))
