# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none

# The `resources` specify the location and version of the 1ES PT.
resources:
    repositories:
        - repository: 1esPipelines
          type: git
          name: 1ESPipelineTemplates/1ESPipelineTemplates
          ref: refs/tags/release

extends:
    # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
    # For non-production pipelines, use "Unofficial" as defined below.
    # For productions pipelines, use "Official".
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
    parameters:
        sdl:
            suppression:
                suppressionFile: $(Build.SourcesDirectory)/azure-pipeline/guardian/SDL/.gdnsuppress
            # Update the pool with your team's 1ES hosted pool.
            pool:
                name: AccessibilityInsights-ubuntu-20.04 # Name of your hosted pool
                image: ubuntu-20.04 # Name of the image in your pool. If not specified, first image of the pool is used
                os: linux # OS of the image. This value cannot be a variable. Allowed values: windows, linux, macOS

            stages:
                - stage: Stage
                  jobs:
                      - job: 'BuildArtifactsAndRunUnitTests'
                  pool:
                      vmImage: 'ubuntu-20.04'
                      demands: npm
                  steps:
                      - template: ./azure-pipeline/build-artifacts-and-run-tests-job.yaml
