# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
openapi: 3.0.0
info:
    version: 1.0.0
    title: Accessibility Insight Service REST API
paths:
    /scans:
        post:
            summary: Create accessibility scan requests
            operationId: createScans
            parameters:
                - name: api-version
                  in: query
                  required: true
                  description: The client API version
                  schema:
                      type: string
                  example: '1.0'
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/ScanRunRequest'
            responses:
                '202':
                    description: Accepted
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/ScanRunResponse'
    '/scans/{scanid}':
        get:
            summary: Get accessibility scan result
            operationId: getScan
            parameters:
                - name: scanid
                  in: path
                  required: true
                  description: The scan request ID
                  schema:
                      type: string
                - name: api-version
                  in: query
                  required: true
                  description: The client API version
                  schema:
                      type: string
                  example: '1.0'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ScanRunResultResponse'
                '400':
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ScanRunErrorResponse'
    /scans/$batch:
        post:
            summary: Get accessibility scan results
            operationId: getScanBatch
            parameters:
                - name: api-version
                  in: query
                  required: true
                  description: The client API version
                  schema:
                      type: string
                  example: '1.0'
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/ScanBatchRequest'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    oneOf:
                                        - $ref: '#/components/schemas/ScanRunResultResponse'
                                        - $ref: '#/components/schemas/ScanRunErrorResponse'
    '/scans/{scanid}/reports/{reportid}':
        get:
            summary: Get accessibility scan report
            operationId: getReport
            parameters:
                - name: scanid
                  in: path
                  required: true
                  description: The scan request ID
                  schema:
                      type: string
                - name: reportid
                  in: path
                  required: true
                  description: The report ID
                  schema:
                      type: string
                - name: api-version
                  in: query
                  required: true
                  description: The client API version
                  schema:
                      type: string
                  example: '1.0'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            example:
                                href: >-
                                    SARIF document per following specification
                                    https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/sarif-v2.1.0-cs01.html
components:
    schemas:
        ScanRunRequest:
            type: object
            required:
                - url
            properties:
                url:
                    type: string
                priority:
                    description: >-
                        Priority values can range from -1000 to 1000, with -1000 being the
                        lowest priority and 1000 being the highest priority. The default
                        value is 0.
                    default: 0
                    type: integer
                scanNotifyUrl:
                    type: string
                deepScan:
                    type: boolean
                    description: Enable crawling and scanning of website's pages under baseURL provided
                site:
                    type: object
                    required:
                        - baseUrl
                    properties:
                        baseUrl:
                            description: The web site root URL to be displayed in 'Scan Details' report section
                            type: string
                        knownPages:
                            type: array
                            items:
                                type: string
                                description: known website page to include in a deep scan run in addition to pages discovered by crawling
                        discoveryPatterns:
                            type: array
                            items:
                                type: string
                                description: RegEx pattern used by web crawler to specify which URLs should website include
                reportGroups:
                    type: array
                    items:
                        required:
                            - consolidatedId
                        properties:
                            consolidatedId:
                                description: The unique report ID for the given reporting period
                                type: string
                authenticationType:
                    description: If present, the type of authentication to be used to authenticate web pages.
                    type: string
                    enum:
                        - azure-ad
                privacyScan:
                    type: object
                    description: If present, the url will be scanned for cookies instead of accessibility issues. In this case, the deepScan and scanNotifyUrl fields will be ignored.
                    required:
                        - cookieBannerType
                    properties:
                        cookieBannerType:
                            description: The type of consent banner in the target page
                            type: string
                            enum:
                                - standard
        ScanRunResponse:
            type: object
            required:
                - url
            properties:
                scanId:
                    type: string
                url:
                    type: string
                error:
                    $ref: '#/components/schemas/WebApiError'
        ScanResult:
            type: object
            required:
                - state
            properties:
                state:
                    $ref: '#/components/schemas/ScanState'
                issueCount:
                    type: integer
                    format: int32
                    minimum: 0
        Links:
            type: object
            required:
                - rel
                - href
            properties:
                rel:
                    type: string
                    default: self
                    enum:
                        - self
                href:
                    type: string
        ScanRun:
            type: object
            required:
                - state
            properties:
                timestamp:
                    description: Full date and time string format as defined by ISO 8601
                    type: string
                error:
                    $ref: '#/components/schemas/ScanRunError'
                state:
                    $ref: '#/components/schemas/RunState'
                pageResponseCode:
                    type: integer
                pageTitle:
                    type: string
        ScanReport:
            type: object
            required:
                - reportId
                - format
                - links
            properties:
                reportId:
                    type: string
                format:
                    type: string
                    description: >-
                        SARIF format specification
                        https://www.oasis-open.org/committees/sarif/charter.php
                    enum:
                        - axe
                        - sarif
                        - html
                        - consolidated.html
                        - json
                        - consolidated.json
                        - page.png
                        - page.mhtml
                links:
                    $ref: '#/components/schemas/Links'
        DeepScanResultItem:
            type: object
            required:
                - scanId
                - url
                - scanRunState
            properties:
                scanId:
                    type: string
                url:
                    type: string
                scanRunState:
                    $ref: '#/components/schemas/RunState'
                scanResultState:
                    $ref: '#/components/schemas/ScanState'
        ScanBatchRequest:
            type: object
            required:
                - scanId
            properties:
                scanId:
                    type: string
        ScanRunResultResponse:
            type: object
            required:
                - scanId
                - url
                - run
            properties:
                scanId:
                    type: string
                url:
                    type: string
                scanResult:
                    $ref: '#/components/schemas/ScanResult'
                deepScanResult:
                    type: array
                    items:
                        $ref: '#/components/schemas/DeepScanResultItem'
                reports:
                    type: array
                    items:
                        $ref: '#/components/schemas/ScanReport'
                run:
                    $ref: '#/components/schemas/ScanRun'
                authentication:
                    $ref: '#/components/schemas/AuthenticationResult'
        WebApiError:
            type: object
            required:
                - code
                - codeId
                - message
            properties:
                code:
                    type: string
                    enum:
                        - ResourceNotFound
                        - InvalidResourceId
                        - InvalidJsonDocument
                        - RequestBodyTooLarge
                        - InvalidURL
                        - InternalError
                        - MissingApiVersionQueryParameter
                        - MissingContentTypeHeader
                        - UnsupportedContentType
                        - UnsupportedApiVersion
                        - OutOfRangePriority
                        - MalformedBody
                        - MissingReleaseVersion
                        - InvalidScanNotifyUrl
                        - InvalidReportGroup
                        - MissingRequiredDeepScanProperties
                        - TooManyKnownPages
                        - InvalidKnownPageURL
                        - DuplicateKnownPage
                codeId:
                    type: integer
                    format: int32
                    minimum: 4001
                    maximum: 5999
                message:
                    type: string
        ScanRunError:
            type: object
            required:
                - code
                - codeId
                - message
            properties:
                code:
                    type: string
                    enum:
                        - InternalError
                        - UrlNavigationTimeout
                        - SslError
                        - ResourceLoadFailure
                        - InvalidUrl
                        - EmptyPage
                        - HttpErrorCode
                        - NavigationError
                        - InvalidContentType
                        - UrlNotResolved
                        - ScanTimeout
                        - BannerXPathNotDetected
                        - AuthenticationError
                codeId:
                    type: integer
                    format: int32
                    minimum: 9001
                    maximum: 9999
                message:
                    type: string
        ScanRunErrorResponse:
            type: object
            required:
                - scanId
                - error
            properties:
                scanId:
                    type: string
                error:
                    $ref: '#/components/schemas/WebApiError'
        ScanState:
            type: string
            default: pending
            enum:
                - pending
                - pass
                - fail
        RunState:
            type: string
            default: pending
            enum:
                - pending
                - accepted
                - queued
                - running
                - completed
                - failed
                - unscannable
        AuthenticationResult:
            type: object
            required:
                - detected
                - state
            properties:
                detected:
                    type: string
                    enum:
                        - unknown
                        - entraId
                state:
                    type: string
                    enum:
                        - succeeded
                        - failed
                        - unauthenticated
