version: 1
update_configs:
    - package_manager: 'javascript'
      directory: '/'
      update_schedule: 'weekly'
      version_requirement_updates: 'increase_versions'
      default_labels:
          - 'category: engineering'
          - 'dependencies'
      commit_message:
          prefix: 'chore'
          include_scope: true
      ignored_updates:
          - match:
                # axe-core updates require enough extra validation
                # on false positives and breaking ai-web, so avoiding
                # dependabot auto-update for them like other deps.
                dependency_name: 'axe-core'
          - match:
                # package is deployed on a server as stand-alone
                # and will require update of deployment script
                # that is not part of dependabot auto-update
                dependency_name: '@axe-core/puppeteer'
          - match:
                # keep node types lock to match with node v12
                dependency_name: '@types/node'
    - package_manager: 'dotnet:nuget'
      directory: '/packages/web-workers/'
      update_schedule: 'daily'
      default_labels:
          - 'category: engineering'
          - 'dependencies'
      commit_message:
          prefix: 'chore'
          include_scope: true
