/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const ScanRunRequest: msRest.CompositeMapper = {
  serializedName: "ScanRunRequest",
  type: {
    name: "Composite",
    className: "ScanRunRequest",
    modelProperties: {
      url: {
        required: true,
        serializedName: "url",
        type: {
          name: "String"
        }
      },
      priority: {
        serializedName: "priority",
        defaultValue: 0,
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const WebApiError: msRest.CompositeMapper = {
  serializedName: "WebApiError",
  type: {
    name: "Composite",
    className: "WebApiError",
    modelProperties: {
      code: {
        required: true,
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      codeId: {
        required: true,
        serializedName: "codeId",
        constraints: {
          InclusiveMaximum: 5999,
          InclusiveMinimum: 4001
        },
        type: {
          name: "Number"
        }
      },
      message: {
        required: true,
        serializedName: "message",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ScanRunResponse: msRest.CompositeMapper = {
  serializedName: "ScanRunResponse",
  type: {
    name: "Composite",
    className: "ScanRunResponse",
    modelProperties: {
      scanId: {
        serializedName: "scanId",
        type: {
          name: "String"
        }
      },
      url: {
        required: true,
        serializedName: "url",
        type: {
          name: "String"
        }
      },
      error: {
        serializedName: "error",
        type: {
          name: "Composite",
          className: "WebApiError"
        }
      }
    }
  }
};

export const ScanResult: msRest.CompositeMapper = {
  serializedName: "ScanResult",
  type: {
    name: "Composite",
    className: "ScanResult",
    modelProperties: {
      state: {
        required: true,
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      issueCount: {
        serializedName: "issueCount",
        constraints: {
          InclusiveMinimum: 0
        },
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const Links: msRest.CompositeMapper = {
  serializedName: "Links",
  type: {
    name: "Composite",
    className: "Links",
    modelProperties: {
      rel: {
        required: true,
        serializedName: "rel",
        defaultValue: 'self',
        type: {
          name: "String"
        }
      },
      href: {
        required: true,
        serializedName: "href",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ScanRunError: msRest.CompositeMapper = {
  serializedName: "ScanRunError",
  type: {
    name: "Composite",
    className: "ScanRunError",
    modelProperties: {
      code: {
        required: true,
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      codeId: {
        required: true,
        serializedName: "codeId",
        constraints: {
          InclusiveMaximum: 9999,
          InclusiveMinimum: 9001
        },
        type: {
          name: "Number"
        }
      },
      message: {
        required: true,
        serializedName: "message",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ScanRun: msRest.CompositeMapper = {
  serializedName: "ScanRun",
  type: {
    name: "Composite",
    className: "ScanRun",
    modelProperties: {
      timestamp: {
        serializedName: "timestamp",
        type: {
          name: "String"
        }
      },
      error: {
        serializedName: "error",
        type: {
          name: "Composite",
          className: "ScanRunError"
        }
      },
      state: {
        required: true,
        serializedName: "state",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ScanReport: msRest.CompositeMapper = {
  serializedName: "ScanReport",
  type: {
    name: "Composite",
    className: "ScanReport",
    modelProperties: {
      reportId: {
        required: true,
        serializedName: "reportId",
        type: {
          name: "String"
        }
      },
      format: {
        required: true,
        serializedName: "format",
        defaultValue: 'sarif',
        type: {
          name: "String"
        }
      },
      links: {
        required: true,
        serializedName: "links",
        type: {
          name: "Composite",
          className: "Links"
        }
      }
    }
  }
};

export const ScanBatchRequest: msRest.CompositeMapper = {
  serializedName: "ScanBatchRequest",
  type: {
    name: "Composite",
    className: "ScanBatchRequest",
    modelProperties: {
      scanId: {
        required: true,
        serializedName: "scanId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ScanRunResultResponse: msRest.CompositeMapper = {
  serializedName: "ScanRunResultResponse",
  type: {
    name: "Composite",
    className: "ScanRunResultResponse",
    modelProperties: {
      scanId: {
        required: true,
        serializedName: "scanId",
        type: {
          name: "String"
        }
      },
      url: {
        required: true,
        serializedName: "url",
        type: {
          name: "String"
        }
      },
      scanResult: {
        serializedName: "scanResult",
        type: {
          name: "Composite",
          className: "ScanResult"
        }
      },
      reports: {
        serializedName: "reports",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ScanReport"
            }
          }
        }
      },
      run: {
        required: true,
        serializedName: "run",
        type: {
          name: "Composite",
          className: "ScanRun"
        }
      }
    }
  }
};

export const ScanRunErrorResponse: msRest.CompositeMapper = {
  serializedName: "ScanRunErrorResponse",
  type: {
    name: "Composite",
    className: "ScanRunErrorResponse",
    modelProperties: {
      scanId: {
        required: true,
        serializedName: "scanId",
        type: {
          name: "String"
        }
      },
      error: {
        required: true,
        serializedName: "error",
        type: {
          name: "Composite",
          className: "WebApiError"
        }
      }
    }
  }
};

export const ScansReportsResponse: msRest.CompositeMapper = {
  serializedName: "ScansReportsResponse",
  type: {
    name: "Composite",
    className: "ScansReportsResponse",
    modelProperties: {
      href: {
        required: true,
        serializedName: "href",
        type: {
          name: "String"
        }
      }
    }
  }
};
